import { QuestionRow, StructuredTags, YearSetOption, SubjectOption, SubtopicOption, QuestionOption } from "../../types";

export interface IQuestionService {
  questions: QuestionRow[];
  loaded: boolean;
  loadMode: "none" | "index" | "full";
  count: Map<string, number>;
  tags: string[];
  sourceUrl: string;
  questionsByUid: Map<string, QuestionRow>;
  detailCache: Map<string, QuestionRow>;
  detailShardCache: Map<string, Record<string, any>>;
  detailShardPromises: Map<string, Promise<any>>;
  pendingLoads: {
    index: Promise<void> | null;
    full: Promise<void> | null;
  };
  SUBJECT_ENUM: { slug: string; label: string }[];
  SUBJECT_LABEL_TO_SLUG: Map<string, string>;
  SUBJECT_SLUG_TO_LABEL: Map<string, string>;
  SUBJECT_PRIORITY: string[];
  SUBJECT_ALIAS_OVERRIDES: Record<string, string[]>;
  SUBJECT_ALIAS_CACHE: Map<string, string[]>;
  MAX_SUBTOPICS_PER_QUESTION: number;
  TOPIC_HIERARCHY: Record<string, string[]>;
  _subtopicLookupCache: Map<string, any>;
  OPTION_LABELS: string[];
  YEAR_SET_TAG_PATTERN: RegExp;
  TITLE_YEAR_SET_PATTERN: RegExp;
  LINK_YEAR_SET_PATTERN: RegExp;


  // Methods
  extractGateOverflowId(link?: string): string | null;
  hashString(value?: string): string;
  buildQuestionUid(question?: any): string;
  hasNativeJoinIdentity(question?: any): boolean;
  getCacheKey(options?: { fullBank?: boolean }): string;
  hasLoadedDataset(options?: { fullBank?: boolean }): boolean;
  getDetailShardKey(question?: any): string;
  getNormalizedSubjectAliases(subject: string): string[];
  getSubjectPriorityIndex(subject: string): number;
  ensureSubjectMaps(): void;
  slugifyToken(value?: string): string;
  getSubjectSlugByLabel(label?: string): string;
  getSubjectLabelBySlug(slug?: string): string;
  normalizeSubjectSlug(value?: string): string | null;
  normalizeTypeToken(rawType?: string): string;
  stripHtmlToText(html?: string): string;
  normalizeQuestionOptionsFromRaw(rawOptions: any): QuestionOption[];
  extractOptionsFromQuestionHtml(questionHtml?: string): QuestionOption[];
  normalizeQuestionOptions(rawOptions: any, questionHtml?: string): QuestionOption[];
  getNormalizedOptions(question?: any): QuestionOption[];
  buildYearSetKey(year: any, setNo: any): string | null;
  parseYearSetKey(rawValue?: string): { year: number; set: number | null; key: string } | null;
  formatYearSetLabel(yearSetKey?: string): string;
  extractYearSetFromTag(rawTag?: string): { year: number; set: number | null } | null;
  extractExamMeta(question?: any): any;
  buildExamMetaFromParsedUid(parsedExamUid?: any, multiSetYears?: Set<number>): any;
  buildExamMetaFromIndexQuestion(question?: any): any;
  getSubtopicLookupForSubject(subjectLabel?: string): Map<string, SubtopicOption>;
  extractCanonicalSubtopics(tags?: string[], subjectLabel?: string): SubtopicOption[];
  resolveCanonicalSubject(question: any): string;
  normalizeQuestion(question?: any): QuestionRow;
  hydrateIndexedQuestion(question?: any): QuestionRow;
  isPracticeExcludedQuestion(question?: any): boolean;
  getCanonicalQuestionKey(question?: any): string;
  getCanonicalQuestionScore(question?: any): number;
  pickPreferredQuestionForSlot(existingQuestion: any, candidateQuestion: any): any;
  finalizeQuestions(questions: QuestionRow[]): QuestionRow[];
  buildDetailedQuestion(rawQuestion: any, indexedQuestion?: any): QuestionRow;
  _processIndexChunked(rows: any[], chunkSize?: number): Promise<QuestionRow[]>;
  _processChunked(rows: any[], chunkSize?: number): Promise<QuestionRow[]>;
  _readCache(options?: { fullBank?: boolean }): any;
  _stripForCache(questions: QuestionRow[]): QuestionRow[];
  _hydrateFromCache(questions: QuestionRow[], options?: { fullBank?: boolean }): QuestionRow[];
  _writeCache(options?: { fullBank?: boolean }): void;
  clearInitCache(): void;
  _loadIndexedDataset(baseUrl: string): Promise<{ sourceUrl: string; questions: QuestionRow[] }>;
  _loadFullBankDataset(baseUrl: string): Promise<any>;
  init(options?: { fullBank?: boolean }): Promise<void>;
  buildIndexes(): void;
  loadDetailShard(shardKey?: string): Promise<any>;
  ensureQuestionDetail(questionOrUid?: any): Promise<QuestionRow | null>;
  getErrorQuestion(title?: string): any;
  getRandomQuestion(tags?: string[]): any;
  getTags(): string[];
  normalizeString(str: string): string;
  getStructuredTags(): StructuredTags;
  getMinMaxYears(): { min: number; max: number };
  getCount(tag: string): number;
}
