/**
 * GlobalDifficultyService — Lazy-loads the static global-difficulty.json
 * and provides per-question difficulty lookups.
 *
 * The file is generated by scripts/pipeline/extract-global-difficulty.mjs
 * using community tags (easy/hard, mark weight) and optionally GateOverflow
 * upvote metadata as signals.
 *
 * Usage:
 *   const gds = GlobalDifficultyService.getInstance(baseUrl);
 *   await gds.load(fetchImpl);
 *   const info = gds.get("go:523089");
 *   // → { score: 20, label: "Easy", signals: ["tag:easy", "marks:1"] }
 */

const LABEL_MAP: Record<string, string> = { E: "Easy", M: "Medium", H: "Hard" };

let singletonInstance: GlobalDifficultyService | null = null;

export interface GlobalDifficultyInfo {
  score: number;
  label: string;
  signals: string[];
}

export interface DifficultyJsonEntry {
  s: number; // score
  l: string; // label (E/M/H)
  g: string[]; // signals
}

export class GlobalDifficultyService {
  private _baseUrl: string;
  private _data: Record<string, DifficultyJsonEntry> | null;
  private _loading: Promise<void> | null;

  /** @param {string} baseUrl — Vite base URL (e.g. "/Gate_QA/") */
  constructor(baseUrl: string = "/") {
    this._baseUrl = String(baseUrl || "/").endsWith("/")
      ? String(baseUrl || "/")
      : `${String(baseUrl || "/")}/`;
    this._data = null;
    this._loading = null;
  }

  /**
   * Get or create a singleton instance.
   * @param {string} [baseUrl]
   */
  static getInstance(baseUrl?: string): GlobalDifficultyService {
    if (!singletonInstance) {
      singletonInstance = new GlobalDifficultyService(baseUrl);
    }
    return singletonInstance;
  }

  /** Reset singleton (for testing). */
  static resetInstance(): void {
    singletonInstance = null;
  }

  /**
   * Lazy-load the difficulty data. Safe to call multiple times;
   * subsequent calls return the cached promise.
   *
   * @param {typeof fetch} fetchImpl
   * @returns {Promise<void>}
   */
  async load(fetchImpl: typeof fetch): Promise<void> {
    if (this._data) return;
    if (this._loading) return this._loading;

    this._loading = (async (): Promise<void> => {
      try {
        const url = `${this._baseUrl}data/global-difficulty.json`;
        const response = await fetchImpl(url, { cache: "force-cache" });
        if (!response?.ok) {
          console.warn("[GlobalDifficulty] Failed to load:", response?.status);
          this._data = {};
          return;
        }
        const json = await response.json();
        this._data = json?.questions || {};
      } catch (err: any) {
        console.warn("[GlobalDifficulty] Load error:", err?.message);
        this._data = {};
      } finally {
        this._loading = null;
      }
    })();

    return this._loading;
  }

  /** Whether data has been loaded. */
  get isLoaded(): boolean {
    return this._data !== null;
  }

  /** Number of scored questions. */
  get size(): number {
    return this._data ? Object.keys(this._data).length : 0;
  }

  /**
   * Get the global difficulty info for a question UID.
   *
   * @param {string} uid — e.g. "go:523089"
   * @returns {{ score: number, label: string, signals: string[] } | null}
   */
  get(uid: string): GlobalDifficultyInfo | null {
    if (!this._data || !uid) return null;
    const entry = this._data[uid];
    if (!entry) return null;

    return {
      score: entry.s || 0,
      label: LABEL_MAP[entry.l] || "Medium",
      signals: entry.g || [],
    };
  }

  /**
   * Get just the numeric score (0–100), or null if unknown.
   * @param {string} uid
   * @returns {number | null}
   */
  getScore(uid: string): number | null {
    const info = this.get(uid);
    return info ? info.score : null;
  }
}
