import * as taxonomy from "./question-service/SubjectTaxonomy.js";
import * as normalizer from "./question-service/QuestionNormalizer.js";
import * as loader from "./question-service/QuestionLoader.js";

export class QuestionService {
  static questions = [];
  static loaded = false;
  static loadMode = "none";
  static count = new Map();
  static tags = [];
  static sourceUrl = "";
  static questionsByUid = new Map();
  static detailCache = new Map();
  static detailShardCache = new Map();
  static detailShardPromises = new Map();
  static pendingLoads = {
    index: null,
    full: null,
  };

  static SUBJECT_ENUM = taxonomy.SUBJECT_ENUM;
  static SUBJECT_LABEL_TO_SLUG = new Map();
  static SUBJECT_SLUG_TO_LABEL = new Map();
  static YEAR_SET_TAG_PATTERN = normalizer.YEAR_SET_TAG_PATTERN;
  static TITLE_YEAR_SET_PATTERN = normalizer.TITLE_YEAR_SET_PATTERN;
  static LINK_YEAR_SET_PATTERN = normalizer.LINK_YEAR_SET_PATTERN;
  static SUBJECT_PRIORITY = taxonomy.SUBJECT_PRIORITY;
  static SUBJECT_ALIAS_OVERRIDES = taxonomy.SUBJECT_ALIAS_OVERRIDES;
  static SUBJECT_ALIAS_CACHE = new Map();
  static OPTION_LABELS = normalizer.OPTION_LABELS;
  static _subtopicLookupCache = new Map();
  static MAX_SUBTOPICS_PER_QUESTION = taxonomy.MAX_SUBTOPICS_PER_QUESTION;
  static TOPIC_HIERARCHY = taxonomy.TOPIC_HIERARCHY;

  static extractGateOverflowId = normalizer.extractGateOverflowId;
  static hashString = normalizer.hashString;
  static buildQuestionUid = normalizer.buildQuestionUid;
  static hasNativeJoinIdentity = normalizer.hasNativeJoinIdentity;
  static getCacheKey = loader.getCacheKey;
  static hasLoadedDataset = loader.hasLoadedDataset;
  static getDetailShardKey = loader.getDetailShardKey;
  static getNormalizedSubjectAliases = taxonomy.getNormalizedSubjectAliases;
  static getSubjectPriorityIndex = taxonomy.getSubjectPriorityIndex;
  static ensureSubjectMaps = taxonomy.ensureSubjectMaps;
  static slugifyToken = taxonomy.slugifyToken;
  static getSubjectSlugByLabel = taxonomy.getSubjectSlugByLabel;
  static getSubjectLabelBySlug = taxonomy.getSubjectLabelBySlug;
  static normalizeSubjectSlug = taxonomy.normalizeSubjectSlug;
  static normalizeTypeToken = normalizer.normalizeTypeToken;
  static stripHtmlToText = normalizer.stripHtmlToText;
  static normalizeQuestionOptionsFromRaw = normalizer.normalizeQuestionOptionsFromRaw;
  static extractOptionsFromQuestionHtml = normalizer.extractOptionsFromQuestionHtml;
  static normalizeQuestionOptions = normalizer.normalizeQuestionOptions;
  static getNormalizedOptions = normalizer.getNormalizedOptions;
  static buildYearSetKey = normalizer.buildYearSetKey;
  static parseYearSetKey = normalizer.parseYearSetKey;
  static formatYearSetLabel = normalizer.formatYearSetLabel;
  static extractYearSetFromTag = normalizer.extractYearSetFromTag;
  static extractExamMeta = normalizer.extractExamMeta;
  static buildExamMetaFromParsedUid = normalizer.buildExamMetaFromParsedUid;
  static buildExamMetaFromIndexQuestion = normalizer.buildExamMetaFromIndexQuestion;
  static getSubtopicLookupForSubject = taxonomy.getSubtopicLookupForSubject;
  static extractCanonicalSubtopics = taxonomy.extractCanonicalSubtopics;
  static resolveCanonicalSubject = taxonomy.resolveCanonicalSubject;
  static normalizeQuestion = normalizer.normalizeQuestion;
  static hydrateIndexedQuestion = normalizer.hydrateIndexedQuestion;
  static isPracticeExcludedQuestion = normalizer.isPracticeExcludedQuestion;
  static getCanonicalQuestionKey = normalizer.getCanonicalQuestionKey;
  static getCanonicalQuestionScore = normalizer.getCanonicalQuestionScore;
  static pickPreferredQuestionForSlot = normalizer.pickPreferredQuestionForSlot;
  static finalizeQuestions = normalizer.finalizeQuestions;
  static buildDetailedQuestion = normalizer.buildDetailedQuestion;
  static _processIndexChunked = loader._processIndexChunked;
  static _processChunked = loader._processChunked;
  static _readCache = loader._readCache;
  static _stripForCache = loader._stripForCache;
  static _hydrateFromCache = loader._hydrateFromCache;
  static _writeCache = loader._writeCache;
  static clearInitCache = loader.clearInitCache;
  static _loadIndexedDataset = loader._loadIndexedDataset;
  static _loadFullBankDataset = loader._loadFullBankDataset;
  static init = loader.init;
  static buildIndexes = loader.buildIndexes;
  static loadDetailShard = loader.loadDetailShard;
  static ensureQuestionDetail = loader.ensureQuestionDetail;
  static getErrorQuestion = loader.getErrorQuestion;
  static getRandomQuestion = loader.getRandomQuestion;
  static getTags = loader.getTags;
  static normalizeString = taxonomy.normalizeString;
  static getStructuredTags = taxonomy.getStructuredTags;
  static getMinMaxYears = loader.getMinMaxYears;
  static getCount = loader.getCount;
}
