/**
 * Comprehensive Database of 500 Premium Motivational & Study Quotes for Students
 * Featuring prominent sections of Indian wisdom (Dr. A.P.J. Abdul Kalam, Gautama Buddha, Swami Vivekananda)
 */
export const STUDENT_QUOTES = [
  // 1-25: A.P.J. Abdul Kalam
  "Dream is not that which you see while sleeping, it is something that does not let you sleep. — Dr. A.P.J. Abdul Kalam",
  "If you want to shine like a sun, first burn like a sun. — Dr. A.P.J. Abdul Kalam",
  "All of us do not have equal talent. But, all of us have an equal opportunity to develop our talents. — Dr. A.P.J. Abdul Kalam",
  "Failure will never overtake me if my determination to succeed is strong enough. — Dr. A.P.J. Abdul Kalam",
  "To succeed in your mission, you must have single-minded devotion to your goal. — Dr. A.P.J. Abdul Kalam",
  "Man needs his difficulties because they are necessary to enjoy success. — Dr. A.P.J. Abdul Kalam",
  "Excellence is a continuous process and not an accident. — Dr. A.P.J. Abdul Kalam",
  "Learning gives creativity, creativity leads to thinking, thinking provides knowledge, knowledge makes you great. — Dr. A.P.J. Abdul Kalam",
  "You have to dream before your dreams can come true. — Dr. A.P.J. Abdul Kalam",
  "If you fail, never give up because F.A.I.L. means 'First Attempt In Learning'. — Dr. A.P.J. Abdul Kalam",
  "End is not the end, in fact E.N.D. means 'Effort Never Dies'. — Dr. A.P.J. Abdul Kalam",
  "If you get 'No' as an answer, remember N.O. means 'Next Opportunity'. — Dr. A.P.J. Abdul Kalam",
  "Look at the sky. We are not alone. The whole universe is friendly to us and conspires only to give the best to those who dream and work. — Dr. A.P.J. Abdul Kalam",
  "Be active! Take on responsibility! Work for the things you believe in. — Dr. A.P.J. Abdul Kalam",
  "Creativity is seeing the same thing but thinking differently. — Dr. A.P.J. Abdul Kalam",
  "Your best teacher is your last mistake. — Dr. A.P.J. Abdul Kalam",
  "It is very easy to defeat someone, but it is very difficult to win someone. — Dr. A.P.J. Abdul Kalam",
  "Climbing to the top demands strength, whether it is to the top of Mount Everest or to the top of your career. — Dr. A.P.J. Abdul Kalam",
  "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life. — Dr. A.P.J. Abdul Kalam",
  "Without your involvement you can't succeed. With your involvement you can't fail. — Dr. A.P.J. Abdul Kalam",
  "Let us sacrifice our today so that our children can have a better tomorrow. — Dr. A.P.J. Abdul Kalam",
  "Small aim is a crime; have great glory. — Dr. A.P.J. Abdul Kalam",
  "To be successful, one must be courageous to accept the mistakes and ready to learn. — Dr. A.P.J. Abdul Kalam",
  "Knowledge without action is useless and irrelevant. — Dr. A.P.J. Abdul Kalam",
  "Science is a beautiful gift to humanity, we should not distort it. — Dr. A.P.J. Abdul Kalam",

  // 26-50: Gautama Buddha
  "The mind is everything. What you think you become. — Gautama Buddha",
  "Every morning we are born again. What we do today is what matters most. — Gautama Buddha",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. — Gautama Buddha",
  "No matter how hard the past, you can always begin again. — Gautama Buddha",
  "Quiet the mind and the soul will speak. — Gautama Buddha",
  "There is no path to happiness: happiness is the path. — Gautama Buddha",
  "Purity or impurity depends on oneself, no one can purify another. — Gautama Buddha",
  "The secret of health for both mind and body is to live in the present moment wisely and earnestly. — Gautama Buddha",
  "To keep the body in good health is a duty, otherwise we shall not be able to keep our mind strong and clear. — Gautama Buddha",
  "Your focus determines your reality. — Gautama Buddha",
  "A disciplined mind brings happiness. — Gautama Buddha",
  "An disciplined mind is a dangerous weapon, but a trained mind is your greatest ally. — Gautama Buddha",
  "One moment can change a day, one day can change a life, one life can change the world. — Gautama Buddha",
  "Patience is key. Remember, a jug fills drop by drop. — Gautama Buddha",
  "Nothing can harm you as much as your own thoughts unguarded. — Gautama Buddha",
  "Peace comes from within. Do not seek it without. — Gautama Buddha",
  "Three things cannot be long hidden: the sun, the moon, and the truth. — Gautama Buddha",
  "Conquer yourself rather than others. — Gautama Buddha",
  "There is nothing more dreadful than the habit of doubt. — Gautama Buddha",
  "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. — Gautama Buddha",
  "To understand everything is to forgive everything. — Gautama Buddha",
  "If you find no companion to walk with, walk alone, like an elephant in the forest. — Gautama Buddha",
  "Dwell on the beauty of life. Watch the stars, and see yourself running with them. — Gautama Buddha",
  "We are shaped by our thoughts; we become what we think. — Gautama Buddha",
  "The root of suffering is attachment. — Gautama Buddha",

  // 51-75: Swami Vivekananda
  "Arise, awake, and stop not till the goal is reached. — Swami Vivekananda",
  "Talk to yourself once a day, otherwise you may miss meeting an excellent person in this world. — Swami Vivekananda",
  "You cannot believe in God until you believe in yourself. — Swami Vivekananda",
  "Take up one idea. Make that one idea your life; think of it, dream of it, live on that idea. — Swami Vivekananda",
  "Strength is life, weakness is death. — Swami Vivekananda",
  "The greatest sin is to think yourself weak. — Swami Vivekananda",
  "Whatever you think, that you will be. If you think yourself weak, weak you will be; if you think yourself strong, strong you will be. — Swami Vivekananda",
  "Believe in yourself and the world will be at your feet. — Swami Vivekananda",
  "The world is the great gymnasium where we come to make ourselves strong. — Swami Vivekananda",
  "In a conflict between the heart and the brain, follow your heart. — Swami Vivekananda",
  "Comfort is no test of truth. Truth is often far from being comfortable. — Swami Vivekananda",
  "All power is within you; you can do anything and everything. — Swami Vivekananda",
  "Do one thing at a time, and while doing it put your whole soul into it to the exclusion of all else. — Swami Vivekananda",
  "We are what our thoughts have made us; so take care about what you think. — Swami Vivekananda",
  "The extreme spirit of cooperation is the hallmark of progress. — Swami Vivekananda",
  "Arise! Awake! And realize the power within your own soul. — Swami Vivekananda",
  "Continuous learning is the secret to a sharp and resilient mind. — Swami Vivekananda",
  "Education is the manifestation of the perfection already in man. — Swami Vivekananda",
  "Every action that helps us manifest our divine nature is good. — Swami Vivekananda",
  "Be not afraid of anything. You will do marvelous work. — Swami Vivekananda",
  "Dare to be free, dare to go as far as your thought leads. — Swami Vivekananda",
  "The greatest religion is to be true to your own nature. Have faith in yourselves. — Swami Vivekananda",
  "Fill the brain with high thoughts, highest ideals, place them day and night before you. — Swami Vivekananda",
  "Condemn none: if you can stretch out a helping hand, do so. — Swami Vivekananda",
  "Stand up, be bold, be strong. Take the whole responsibility on your own shoulders. — Swami Vivekananda",

  // 76-100: Other Indian Wisdom (Gandhi, Tagore, Chanakya, Nehru, Kalam & Buddha Mix)
  "Be the change that you wish to see in the world. — Mahatma Gandhi",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi",
  "The future depends on what you do today. — Mahatma Gandhi",
  "Satisfaction lies in the effort, not in the attainment. Full effort is full victory. — Mahatma Gandhi",
  "Strength does not come from physical capacity. It comes from an indomitable will. — Mahatma Gandhi",
  "You must not lose faith in humanity. — Mahatma Gandhi",
  "The weak can never forgive. Forgiveness is the attribute of the strong. — Mahatma Gandhi",
  "An ounce of practice is worth more than tons of preaching. — Mahatma Gandhi",
  "You cannot cross the sea merely by standing and staring at the water. — Rabindranath Tagore",
  "Faith is the bird that feels the light when the dawn is still dark. — Rabindranath Tagore",
  "Let us not pray to be sheltered from dangers but to be fearless when facing them. — Rabindranath Tagore",
  "Everything comes to us that belongs to us if we create the capacity to receive it. — Rabindranath Tagore",
  "Facts are many, but the truth is one. — Rabindranath Tagore",
  "The butterfly counts not months but moments, and has time enough. — Rabindranath Tagore",
  "We read the world wrong and say that it deceives us. — Rabindranath Tagore",
  "Education means enabling the mind to find out that ultimate truth which emancipates us from bondages. — Rabindranath Tagore",
  "Before you start some work, always ask yourself three questions: Why am I doing it, What the results might be, and Will I be successful. — Chanakya",
  "Once you start a working on something, don't be afraid of failure and don't abandon it. — Chanakya",
  "The biggest guru-mantra is: never share your secrets with anybody. It will destroy you. — Chanakya",
  "Education is the best friend. An educated person is respected everywhere. — Chanakya",
  "A man is great by deeds, not by birth. — Chanakya",
  "Learn from the mistakes of others... you can't live long enough to make them all yourselves. — Chanakya",
  "Time is not measured by the passing of years but by what one does, what one feels, and what one achieves. — Jawaharlal Nehru",
  "Failure comes only when we forget our ideals and objectives and principles. — Jawaharlal Nehru",
  "Action to be effective must be directed to a clearly conceived goal. — Jawaharlal Nehru",

  // 101-200: Classic & Modern Western Educational Philosophy
  "The secret of getting ahead is getting started. — Mark Twain",
  "It always seems impossible until it's done. — Nelson Mandela",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Success is the sum of small efforts, repeated day in and day out. — Robert Collier",
  "The best way to predict the future is to create it. — Abraham Lincoln",
  "There are no shortcuts to any place worth going. — Beverly Sills",
  "Strive for progress, not perfection.",
  "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "Don't let what you cannot do interfere with what you can do. — John Wooden",
  "Focus on the journey, not the destination.",
  "Make each day your masterpiece. — John Wooden",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. — Brian Herbert",
  "It is not that I'm so smart, it's just that I stay with problems longer. — Albert Einstein",
  "Failure is simply the opportunity to begin again, this time more intelligently. — Henry Ford",
  "The expert in anything was once a beginner. — Helen Hayes",
  "Mistakes are proof that you are trying.",
  "Learn from yesterday, live for today, hope for tomorrow. — Albert Einstein",
  "You are more capable than you know.",
  "Genius is 1% talent and 99% hard work. — Albert Einstein",
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "A person who never made a mistake never tried anything new. — Albert Einstein",
  "Ninety-nine percent of the failures come from people who have the habit of making excuses. — George Washington Carver",
  "Action is the foundational key to all success. — Pablo Picasso",
  "The beautiful thing about learning is that no one can take it away from you. — B.B. King",
  "The secret to success is to do the common things uncommonly well. — John D. Rockefeller",
  "If you can dream it, you can do it. — Walt Disney",
  "Procrastination makes easy things hard and hard things harder. — Mason Cooley",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "Education is the passport to the future, for tomorrow belongs to those who prepare for it today. — Malcolm X",
  "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
  "Everything is hard before it is easy. — Goethe",
  "It's not about having time, it's about making time.",
  "Small daily improvements over time lead to stunning results. — Robin Sharma",
  "Perseverance is not a long race; it is many short races one after the other. — Walter Elliot",
  "The only place where success comes before work is in the dictionary. — Vidal Sassoon",
  "A year from now you may wish you had started today. — Karen Lamb",
  "There are no traffic jams on the extra mile. — Roger Staubach",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "To achieve great things, two things are needed: a plan and not quite enough time. — Leonard Bernstein",
  "Hard work beats talent when talent doesn't work hard. — Tim Notke",
  "The roots of education are bitter, but the fruit is sweet. — Aristotle",
  "If you fail to plan, you are planning to fail. — Benjamin Franklin",
  "Patience is a key element of success. — Bill Gates",
  "Defeat is not the worst of failures. Not to have tried is the true failure. — George Edward Woodberry",
  "Motivation is what gets you started. Habit is what keeps you going. — Jim Ryun",
  "Doubt kills more dreams than failure ever will. — Karim Seddiki",
  "Courage doesn't always roar. Sometimes courage is the quiet voice saying, 'I will try again tomorrow.' — Mary Anne Radmacher",
  "Big journeys begin with small steps.",
  "Don't wish it were easier. Wish you were better. — Jim Rohn",
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
  "Quality is not an act, it is a habit. — Aristotle",
  "He who asks is a fool for five minutes, but he who does not ask remains a fool forever. — Chinese Proverb",
  "Great things are done by a series of small things brought together. — Vincent Van Gogh",
  "Do what you must do until you can do what you want to do. — Oprah Winfrey",
  "If you are working on something that you really care about, the vision pulls you. — Steve Jobs",
  "The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson",
  "Preparation is the key to success. — Alexander Graham Bell",
  "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "You get what you focus on, so focus on what you want.",
  "Be so good they can't ignore you. — Steve Martin",
  "Your time is limited, so don't waste it living someone else's life. — Steve Jobs",
  "If you want to fly, you have to give up the things that weigh you down. — Toni Morrison",
  "Don't count the days, make the days count. — Muhammad Ali",
  "The best way to get started is to quit talking and begin doing. — Walt Disney",
  "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until focused. — Alexander Graham Bell",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Will Durant",
  "Aim for the moon. If you miss, you may hit a star. — W. Clement Stone",
  "Opportunity is missed by most because it is dressed in overalls and looks like work. — Thomas Edison",
  "Never give up on a dream just because of the time it will take. The time will pass anyway. — Earl Nightingale",
  "Education is not the filling of a pail, but the lighting of a fire. — William Butler Yeats",
  "Be yourself; everyone else is already taken. — Oscar Wilde",
  "No masterpiece was ever created by a lazy artist.",
  "There is no substitute for hard work. — Thomas Edison",
  "The mind once enlightened cannot again become dark. — Thomas Paine",
  "The bad news is time flies. The good news is you're the pilot. — Michael Altshuler",
  "Your talent is God's gift to you. What you do with it is your gift back. — Leo Buscaglia",
  "Change your thoughts and you change your world. — Norman Vincent Peale",
  "Happiness is not something ready made. It comes from your own actions. — Dalai Lama",
  "Keep your face always toward the sunshine and shadows will fall behind. — Walt Whitman",
  "Act as if what you do makes a difference. It does. — William James",
  "Success doesn't come to you, you go to it. — Marva Collins",
  "Determine that the thing can and shall be done, and then we shall find the way. — Abraham Lincoln",
  "Press forward. Do not stop, do not linger in your journey, but strive for the mark. — George Whitefield",
  "Out of difficulties grow miracles. — Jean de La Bruyere",
  "With the new day comes new strength and new thoughts. — Eleanor Roosevelt",
  "Your limit is only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "It's going to be hard, but hard does not mean impossible.",
  "Sometimes later becomes never. Do it now.",
  "Great things never come from comfort zones.",
  "Mastery is a journey, not a single milestone. Keep practicing!",

  // 201-300: Quotes on Focus, Persistence, and Overcoming Obstacles
  "The successful warrior is the average man, with laser-like focus. — Bruce Lee",
  "Focus is a matter of deciding what things you're not going to do. — John Carmack",
  "Keep your eyes on the stars and your feet on the ground. — Theodore Roosevelt",
  "Energy is the essence of life. Focus that energy. — Oprah Winfrey",
  "Concentration is the secret of strength in politics, in war, in trade, in short in all management. — Ralph Waldo Emerson",
  "Only through focus can you do world-class things, no matter how capable you are. — Bill Gates",
  "It is during our darkest moments that we must focus to see the light. — Aristotle",
  "I don't focus on what I'm up against. I focus on my goals and try to ignore the rest. — Venus Williams",
  "You cannot depend on your eyes when your imagination is out of focus. — Mark Twain",
  "A clear vision, backed by definite plans, gives you a tremendous feeling of strength. — Brian Tracy",
  "Persistence guarantees that results are inevitable. — Paramahansa Yogananda",
  "Most of the important things in the world have been accomplished by people who kept trying. — Dale Carnegie",
  "Through perseverance many people win success out of what seemed destined to be failure. — Benjamin Disraeli",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "With ordinary talent and extraordinary perseverance, all things are attainable. — Thomas Fowell Buxton",
  "Rivers know this: there is no hurry. We shall get there some day. — A.A. Milne",
  "The path to success is to take massive, focused action. — Tony Robbins",
  "Success is not a destination, it's a constant journey of improvement.",
  "The difference between the difficult and the impossible is that the impossible takes a little longer.",
  "Great things are done by a series of small, daily actions.",
  "Keep going. Your hardest moments often lead to your greatest triumphs.",
  "The key to success is to focus on goals, not obstacles.",
  "You are capable of doing difficult things.",
  "Every champion was once a contender that refused to give up. — Rocky Balboa",
  "Do not let the behavior of others destroy your inner peace. — Dalai Lama",
  "The major key to your better future is you. — Jim Rohn",
  "If you want to be happy, set a goal that commands your thoughts, liberates your energy, and inspires your hopes. — Andrew Carnegie",
  "The only time you fail is when you fall down and stay down. — Stephen Richards",
  "Do not fear going slowly, fear only standing still. — Chinese Proverb",
  "Continuous effort, not strength or intelligence, is the key to unlocking our potential. — Winston Churchill",
  "He who is brave is free. — Seneca",
  "A stumbling block to the pessimist is a stepping-stone to the optimist. — Eleanor Roosevelt",
  "Difficulties strengthen the mind, as labor does the body. — Seneca",
  "There is no gain without struggle. — Richard Evans",
  "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
  "If you are going through hell, keep going. — Winston Churchill",
  "The block of granite which was an obstacle in the pathway of the weak becomes a stepping-stone in the pathway of the strong. — Carlyle",
  "Patience and perseverance have a magical effect before which difficulties disappear. — John Quincy Adams",
  "Fall seven times, stand up eight. — Japanese Proverb",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "The true measure of a man is not how he behaves in moments of comfort, but how he stands at times of challenge. — Martin Luther King Jr.",
  "An obstacle is often a stepping stone. — Prescott",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
  "Out of clutter, find simplicity. From discord, find harmony. In the middle of difficulty lies opportunity. — Albert Einstein",
  "It is not the mountain we conquer, but ourselves. — Sir Edmund Hillary",
  "Problems are not stop signs, they are guidelines. — Robert Schuller",
  "Hard times create strong men. Strong men create good times.",
  "Your life does not get better by chance, it gets better by change. — Jim Rohn",
  "Nurture your mind with great thoughts, for you will never go any higher than you think. — Benjamin Disraeli",
  "If you want to conquer fear, don't sit home and think about it. Go out and get busy. — Dale Carnegie",
  "You must do the thing you think you cannot do. — Eleanor Roosevelt",
  "Believe that life is worth living and your belief will help create the fact. — William James",
  "Build your own dreams, or someone else will hire you to build theirs. — Farrah Gray",
  "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible. — Francis of Assisi",
  "I am not a product of my circumstances. I am a product of my decisions. — Stephen Covey",
  "The best revenge is massive success. — Frank Sinatra",
  "You cannot pull anyone up unless you are standing on higher ground. — Booker T. Washington",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "Opportunities multiply as they are seized. — Sun Tzu",
  "Small deeds done are better than great deeds planned. — Peter Marshall",
  "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
  "Life is 10% what happens to me and 90% of how I react to it. — John Maxwell",
  "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson",
  "We cannot solve our problems with the same thinking we used when we created them. — Albert Einstein",
  "Success is not in what you have, but who you have become.",
  "Do not pray for an easy life, pray for the strength to endure a difficult one. — Bruce Lee",
  "If you don't stand for something you will fall for anything. — Malcolm X",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself. — Rumi",
  "Be curious, not judgmental. — Walt Whitman",
  "You only live once, but if you do it right, once is enough. — Mae West",
  "The function of leadership is to produce more leaders, not more followers. — Ralph Nader",
  "Don't compromise yourself. You are all you've got. — Janis Joplin",
  "There is no wealth like knowledge, and no poverty like ignorance. — Ali ibn Abi Talib",
  "Write it on your heart that every day is the best day in the year. — Ralph Waldo Emerson",
  "Make your life a mission, not a career.",
  "To shine your brightest light is to be who you truly are.",
  "The standard you walk past is the standard you accept. — David Morrison",
  "A mind is like a parachute. It doesn't work if it isn't open. — Frank Zappa",
  "Knowledge is power. Information is liberating. Education is the premise of progress. — Kofi Annan",
  "An investment in knowledge always pays the best interest. — Benjamin Franklin",
  "He who has a why to live can bear almost any how. — Friedrich Nietzsche",
  "To know that we know what we know, and that we do not know what we do not know, that is true knowledge. — Copernicus",
  "Integrity is doing the right thing, even when no one is watching. — C.S. Lewis",
  "If you want to go fast, go alone. If you want to go far, go together. — African Proverb",
  "Be kind, for everyone you meet is fighting a harder battle. — Plato",
  "Never ruin a good apology with an excuse. — Benjamin Franklin",
  "Success is not measured by what you accomplish, but by the opposition you have encountered. — Booker T. Washington",
  "Excellence is not a singular act, but a habit.",
  "You must do the things you think you cannot do. — Eleanor Roosevelt",
  "If you tell the truth, you don't have to remember anything. — Mark Twain",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "The journey of a thousand miles begins with one step. — Lao Tzu",
  "The high destiny of individual is to serve rather than to rule. — Albert Einstein",
  "It is not how much we have, but how much we enjoy, that makes happiness. — Charles Spurgeon",
  "A warm smile is the universal language of kindness. — William Arthur Ward",
  "Truth is powerful and it prevails. — Sojourner Truth",
  "Hope is a waking dream. — Aristotle",
  "Silence is a source of great strength. — Lao Tzu",
  "A good head and a good heart are always a formidable combination. — Nelson Mandela",
  "Nothing is permanent in this wicked world, not even our troubles. — Charlie Chaplin",

  // 301-400: Quotes on Learning, Wisdom, and Intellectual Growth
  "Learning is not compulsory. Neither is survival. — W. Edwards Deming",
  "The only real mistake is the one from which we learn nothing. — Henry Ford",
  "Wisdom begins in wonder. — Socrates",
  "The mind is not a vessel to be filled, but a fire to be kindled. — Plutarch",
  "He who learns but does not think is lost! He who thinks but does not learn is in great danger. — Confucius",
  "The authority of those who teach is often an obstacle to those who want to learn. — Cicero",
  "You learn something every day if you pay attention. — Ray LeBlond",
  "The simple act of paying attention can take you a long way. — Keanu Reeves",
  "To learn is to live. To live is to grow. To grow is to improve.",
  "Learning is a treasure that will follow its owner everywhere. — Chinese Proverb",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. — Dr. Seuss",
  "Never discourage anyone who continually makes progress, no matter how slow. — Plato",
  "Any fool can know. The point is to understand. — Albert Einstein",
  "There is no wealth like knowledge, and no poverty like ignorance. — Buddha",
  "Wisdom is not a product of schooling but of the lifelong attempt to acquire it. — Albert Einstein",
  "The threshold of the temple of wisdom is a knowledge of our own ignorance. — Charles Spurgeon",
  "Curiosity is the wick in the candle of learning. — William Arthur Ward",
  "Learning is the only thing the mind never exhausts, never fears, and never regrets. — Leonardo da Vinci",
  "He who opens a school door, closes a prison. — Victor Hugo",
  "Mastering others is strength. Mastering yourself is true power. — Lao Tzu",
  "You cannot open a book without learning something. — Confucius",
  "The purpose of learning is growth, and our minds, unlike our bodies, can continue growing as long as we live. — Mortimer Adler",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. — Gandhi",
  "Knowledge is of no value unless you put it into practice. — Anton Chekhov",
  "A wise man will make more opportunities than he finds. — Francis Bacon",
  "Real knowledge is to know the extent of one's ignorance. — Confucius",
  "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us. — Socrates",
  "The beautiful thing about learning is nobody can take it away from you. — B.B. King",
  "Share your knowledge. It is a way to achieve immortality. — Dalai Lama",
  "Wisdom is the reward you get for a lifetime of listening when you would have preferred to talk. — Mark Twain",
  "A prudent question is one half of wisdom. — Francis Bacon",
  "We do not receive wisdom; we must discover it for ourselves. — Marcel Proust",
  "Knowledge has to be improved, challenged, and increased constantly, or it vanishes. — Peter Drucker",
  "The learning process is something you can never stop. — Joan Lunden",
  "I am still learning. — Michelangelo at age 87",
  "Change is the end result of all true learning. — Leo Buscaglia",
  "The classroom of the world is always in session.",
  "Intellectual growth should commence at birth and cease only at death. — Albert Einstein",
  "The mind, once stretched by a new idea, never returns to its original dimensions. — Ralph Waldo Emerson",
  "There is no end to education. It is not that you read a book, pass an examination, and finish with education. — Jiddu Krishnamurti",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "Take the attitude of a student, never be too big to ask questions. — Og Mandino",
  "Education is the movement from darkness to light. — Allan Bloom",
  "He who is not everyday conquering some fear has not learned the secret of life. — Ralph Waldo Emerson",
  "Knowledge is the eye of desire and can become the pilot of the soul. — Will Durant",
  "The key to growth is the introduction of higher dimensions of consciousness into our awareness. — Lao Tzu",
  "To acquire knowledge, one must study; but to acquire wisdom, one must observe. — Marilyn vos Savant",
  "Be curious. Read widely. Try new things. What people call intelligence just boils down to curiosity. — Aaron Swartz",
  "Wisdom is the power to put our time and our knowledge to the proper use. — Thomas J. Watson",
  "True education is about learning how to think, not what to think. — Gerald Groeland",
  "You cannot teach a man anything; you can only help him find it within himself. — Galileo",
  "The highest result of education is tolerance. — Helen Keller",
  "A graduation ceremony is an event where the commencement speaker tells thousands of students dressed in identical caps and gowns that 'individuality' is the key to success. — Robert Orben",
  "What is a school? A place where children go to find out what they already are.",
  "Standardized testing is not the measure of your intellect. It is merely a measure of your test-taking ability.",
  "Learn to listen. Opportunity sometimes knocks very softly. — Sandra K. Aldrich",
  "The roots of education are bitter, but the fruit is sweet. — Aristotle",
  "Never let formal education get in the way of your learning. — Mark Twain",
  "Self-education is, I firmly believe, the only kind of education there is. — Isaac Asimov",
  "Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in. — Isaac Asimov",
  "Intelligence is the ability to adapt to change. — Stephen Hawking",
  "Quiet people have the loudest minds. — Stephen Hawking",
  "Remember to look up at the stars and not down at your feet. — Stephen Hawking",
  "One, remember to look up at the stars and not down at your feet. Two, never give up work. — Stephen Hawking",
  "There is no substitute for hard work. — Thomas Edison",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  "Genius is one percent inspiration and ninety-nine percent perspiration. — Thomas Edison",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. — Thomas Edison",
  "To do more than is required of you is the first step toward getting ahead.",
  "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing. — George Bernard Shaw",
  "Do not wait for the perfect moment. Take the moment and make it perfect.",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "If you haven't found it yet, keep looking. Don't settle. — Steve Jobs",
  "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become. — Steve Jobs",
  "Stay hungry. Stay foolish. — Steve Jobs",
  "Innovation distinguishes between a leader and a follower. — Steve Jobs",
  "Details matter, it's worth waiting to get it right. — Steve Jobs",
  "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected. — Steve Jobs",
  "The people who are crazy enough to think they can change the world are the ones who do. — Steve Jobs",
  "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time. — Steve Jobs",
  "Patience, persistence, and perspiration make an unbeatable combination for success. — Napoleon Hill",
  "Strength does not come from winning. Your struggles develop your strengths. — Arnold Schwarzenegger",
  "If you want to achieve excellence, you can get there today. As of this second, cease doing less-than-excellent work. — Thomas J. Watson",
  "Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. — Oprah Winfrey",
  "I don't believe in failure. It is not failure if you enjoyed the process. — Oprah Winfrey",
  "The biggest adventure you can take is to live the life of your dreams. — Oprah Winfrey",
  "You get in life what you have the courage to ask for. — Oprah Winfrey",
  "Failure is another steppingstone to greatness. — Oprah Winfrey",
  "Doing the best at this moment puts you in the best place for the next moment. — Oprah Winfrey",
  "Real integrity is doing the right thing, knowing that nobody's going to know whether you did it or not. — Oprah Winfrey",
  "Excellence is the best deterrent to racism or sexism. — Oprah Winfrey",
  "Success is not final; failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
  "Continuous effort - not strength or intelligence - is the key to unlocking our potential. — Winston Churchill",
  "Never, never, never give up. — Winston Churchill",
  "The price of greatness is responsibility. — Winston Churchill",
  "Attitude is a little thing that makes a big difference. — Winston Churchill",
  "It is a mistake to look too far ahead. Only one link in the chain of destiny can be handled at a time. — Winston Churchill",
  "Success is stumbling from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "To improve is to change; to be perfect is to change often. — Winston Churchill",
  "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty. — Winston Churchill",
  "We make a living by what we get, but we make a life by what we give. — Winston Churchill",

  // 401-500: Power Study Quotes & Daily Consistency Sparks
  "The secret to a rich study session is to put away your phone. Focus is absolute.",
  "Your desk is your laboratory. Keep it clean, keep it focused.",
  "A calendar planned is a battle half won. Track your goals daily.",
  "Write down what you study. Active recall increases retention by 150%.",
  "Explain a concept to a child. If you can't, you don't understand it yet. — Richard Feynman",
  "I fell in love with physics because it's a way of understanding the universe. — Richard Feynman",
  "The first principle is that you must not fool yourself and you are the easiest person to fool. — Richard Feynman",
  "What I cannot create, I do not understand. — Richard Feynman",
  "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible. — Richard Feynman",
  "If you want to master a concept, teach it to someone else. — Richard Feynman",
  "Don't worry about what others are doing. Better your own scores day by day.",
  "Every solved question is a brick in the fortress of your confidence.",
  "Study when others are sleeping. Work when others are playing. Enjoy when others are wishing.",
  "Success isn't always about greatness. It's about consistency. — Dwayne Johnson",
  "Blood, sweat, and respect. First two you give, last one you earn. — Dwayne Johnson",
  "Success at anything will always come down to this: focus and effort. And we control both. — Dwayne Johnson",
  "Consistency is the companion of success. Choose it daily.",
  "Your GATE preparation is not a sprint, it is a glorious marathon. Keep pacing.",
  "The double-loop of practice: solve, analyze error, learn concept, repeat.",
  "A bookmarked question is a future score waiting to be unlocked.",
  "Never feel bad about failing a practice question. It's cheap practice before the main battle.",
  "A year of consistent study can rewrite the next thirty years of your career.",
  "Your future self is watching you right now through your choices. Make them proud.",
  "The best preparation for tomorrow is doing your best today. — H. Jackson Brown Jr.",
  "Don't let yesterday take up too much of today. — Will Rogers",
  "You learn more from failure than from success. Don't let it stop you. — Unknown",
  "If you're working on something exciting that you really care about, you don't have to be pushed.",
  "People who are crazy enough to think they can change the world, do. — Rob Siltanen",
  "We may encounter many defeats but we must not be defeated. — Maya Angelou",
  "You alone are enough. You have nothing to prove to anybody. — Maya Angelou",
  "All great achievements require time. — Maya Angelou",
  "If you don't like something, change it. If you can't change it, change your attitude. — Maya Angelou",
  "Nothing will work unless you do. — Maya Angelou",
  "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that. — Maya Angelou",
  "Be a rainbow in somebody else's cloud. — Maya Angelou",
  "Courage is the most important of all the virtues because without courage, you can't practice any other. — Maya Angelou",
  "Excellence is an art won by training and habituation. — Aristotle",
  "Excellence, then, is a habit, not an act. — Aristotle",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
  "Knowing yourself is the beginning of all wisdom. — Aristotle",
  "It is the mark of an educated mind to be able to entertain a thought without accepting it. — Aristotle",
  "Educating the mind without educating the heart is no education at all. — Aristotle",
  "Hope is a waking dream. — Aristotle",
  "No great genius has ever existed without some touch of madness. — Aristotle",
  "Happiness depends upon ourselves. — Aristotle",
  "The roots of education are bitter, but the fruit is sweet. — Aristotle",
  "Pleasure in the job puts perfection in the work. — Aristotle",
  "Do not train a child to learn by force or harshness; but direct them to it by what amuses their minds. — Plato",
  "The beginning is the most important part of the work. — Plato",
  "Knowledge which is acquired under compulsion obtains no hold on the mind. — Plato",
  "There are two things a person should never be angry at: what they can help, and what they cannot. — Plato",
  "The direction in which education starts a man will determine his future in life. — Plato",
  "Wisdom is a high-yield asset that compounds continuously.",
  "Never hesitate to write down intermediate steps. Clear execution prevents silly NAT errors.",
  "Consistency is the ultimate competitive advantage. Most people give up early.",
  "The best code is no code, and the best practice is deliberate practice.",
  "A calm mind is a powerful calculator. Take deep breaths during practice.",
  "Take regular Pomodoro breaks. 25 minutes of deep focus, 5 minutes of rest keeps mental fatigue away.",
  "Practice builds myelin. Deliberate repetition physically shapes your brain paths for speed.",
  "Enjoy the process of solving. The puzzle is the reward, the score is just a side effect.",
  "Focus on the fundamental concepts. Memorized tricks fail when the GATE paper twists the question.",
  "Your mind is a muscle. Give it heavy loads to lift, then give it recovery time.",
  "Every hard NAT question you conquer expands your logical capacity.",
  "Struggling with a problem for 30 minutes is where the actual cognitive growth happens.",
  "Do not look at the answer key too quickly. Fight the problem until it surrenders.",
  "A neat error log is the diary of a future topper.",
  "Sleep is the consolidator of memory. Get 7 hours of rest to let your brain lock in what you studied.",
  "GATE CS is a test of clear basics. Revise your math, discrete logic, and core algorithms weekly.",
  "Mastery is a journey, not a single milestone. Keep practicing!",
  "Be consistent. Be curious. Be indomitable. Your success is inevitable."
];

/**
 * Deterministically pick a quote for the student based on date and time
 */
export const getQuoteForToday = () => {
  if (typeof window === "undefined") return STUDENT_QUOTES[0];
  
  const now = new Date();
  // Mix day, month, and hour to get a rotating quote index that stays consistent for the hour
  const seed = now.getDate() * 19 + now.getMonth() * 37 + now.getHours() * 7;
  const index = Math.abs(seed) % STUDENT_QUOTES.length;
  
  return STUDENT_QUOTES[index];
};
